//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourcesManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to àùãåã
        ///áàø ùáò
        ///àù÷ìåï
        ///øäè
        ///÷øééú âú
        ///àéìú
        ///ðúéáåú
        ///ãéîåðä
        ///àåô÷éí
        ///ùãøåú
        ///òøã
        ///÷øééú îìàëé
        ///éøåùìéí
        ///áéú ùîù
        ///øàùåï ìöéåï
        ///ôúç ú÷ååä
        ///ðúðéä
        ///øçåáåú
        ///ëôø ñáà
        ///ìåã
        ///øàù äòéï
        ///éáðä
        ///àìòã
        ///úì àáéá
        ///øîú âï
        ///áú éí
        ///÷øééú àåðå.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enhe {
            get {
                object obj = ResourceManager.GetObject("enhe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_plus {
            get {
                object obj = ResourceManager.GetObject("green_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à
        ///á
        ///â
        ///ã
        ///ä
        ///å
        ///æ
        ///ç
        ///è
        ///é
        ///ë
        ///ì
        ///î
        ///ð
        ///ñ
        ///ò
        ///ô
        ///ö
        ///÷
        ///ø
        ///ù
        ///ú
        ///ê
        ///í
        ///ï
        ///ó
        ///õ.
        /// </summary>
        internal static string hebrewletters {
            get {
                return ResourceManager.GetString("hebrewletters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ëäï
        ///ìåé
        ///îæøçé
        ///ôøõ
        ///áéèåï
        ///ãäï
        ///àáøäí
        ///àâáàøéä
        ///ôøéãîï
        ///îìëä
        ///àæåìàé
        ///éåñó
        ///îçàîéã
        ///ëõ
        ///â&apos;áàøéï
        ///ãåã
        ///òîø
        ///çãã
        ///àåçéåï
        ///âáàé
        ///ç&apos;èéá
        ///áï ãåã
        ///àãøé
        ///÷ìééï
        ///çï
        ///ùôéøà
        ///æåòáé
        ///îçàâ&apos;ðä
        ///èì
        ///ìåéï
        ///îùä
        ///çæï
        ///àåçðä
        ///ñåàòã
        ///âåìï
        ///ñâì
        ///àùëðæé
        ///éöç÷
        ///áø
        ///éò÷á
        ///îåø
        ///ùìåí
        ///àìéäå
        ///ãééï
        ///ñåéñä
        ///ìáéà
        ///àìáæ
        ///ùîù
        ///àèéàñ
        ///áëø
        ///ðçåí
        ///ùèøï
        ///ùøòáé
        ///àìåï
        ///øåæðáøâ
        ///îîï
        ///áï çîå
        ///îéîåï
        ///ùçø
        ///å÷ðéï
        ///ùùåï
        ///òåáãéä
        ///àñåìéï
        ///ùåøõ
        ///îàéø
        ///åééñ
        ///âøéðáøâ
        ///çñï
        ///àîñìí
        ///âåìãùèééï
        ///áøåê
        ///èàäà
        ///îñàøåä
        ///òæøà
        ///éôøç
        ///ôìãîï
        ///øåáéï
        ///äøàì
        ///ñìàîä
        ///ñáâ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastnames {
            get {
                return ResourceManager.GetString("lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap missing_profile_photo {
            get {
                object obj = ResourceManager.GetObject("missing-profile-photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to àáé
        ///àáéàåø
        ///àáéàì
        ///àáéá
        ///àáéâãåø
        ///àáéãåø
        ///àáéãï
        ///àáéä
        ///àáéäå
        ///àáéçé
        ///àáéðåòí
        ///àáéðø
        ///àáéòã
        ///àáéø
        ///àáéùé
        ///àáéúø
        ///àáðø
        ///àáøäí
        ///àáùìåí
        ///àâí
        ///àãé
        ///àãéø
        ///àãí
        ///àãø
        ///àãøéàï
        ///àäåã
        ///àäøåï
        ///àåãé
        ///àåäã
        ///àåìéáø
        ///àåï
        ///àåôéø
        ///àåô÷
        ///àåôøé
        ///àåø
        ///àåøàì
        ///àåøåï
        ///àåøé
        ///àåøéàì
        ///àåøéàï
        ///àåøéä
        ///àåøééï
        ///àåøéï
        ///àåøï
        ///àåùé÷
        ///àåùï
        ///àåùø
        ///àåùøé
        ///àçéä
        ///àçéùé
        ///àéá
        ///àéãå
        ///àééì
        ///àééìåï
        ///àéìàé
        ///àéìåï
        ///àéìåø
        ///àéìé
        ///àéìéé
        ///àéìï
        ///àéìòàé
        ///àéîøé
        ///àéöé÷
        ///àéúé
        ///àéúéàì
        ///àéúí
        ///àéúîø
        ///àéúï
        ///àìàåø
        ///àìàåøé
        ///àìãã
        ///àìãø
        ///àìåï
        ///àìçé
        ///àìçðï
        ///àìé
        ///àìéàá
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort {
            get {
                object obj = ResourceManager.GetObject("sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ìëéù
        ///ìåçîéäâéèàåú
        ///ìîøçá
        ///îáöò÷ãù
        ///îâã 
        ///îâéãå 
        ///îåãéòéï
        ///îåøï
        ///îåäìéáø
        ///îåøéä
        ///îñãä
        ///îòééïçøåã
        ///îöãä
        ///îøâðéú
        ///îøãëé
        ///ðäøãòà
        ///ðååä øòéí
        ///ðåøãàå
        ///ðåøéú
        ///ðçì áùåø
        ///ðçì òîåã
        ///ðçì ÷ãøåï
        ///ðçìùåø÷
        ///ðçîéä
        ///ðçùåï
        ///ðèó
        ///ðéì&quot;é
        ///ðöðä
        ///ðòîé
        ///ñáéåï
        ///ñåìã
        ///ðúðéäå
        ///ñáéåï
        ///ñåìã
        ///ñå÷åìåá
        ///ñéâìéú
        ///ñéðé
        ///ñìò 
        ///ñîãø
        ///ñðä îùä
        ///ñðåðéú
        ///ñðù
        ///òáãú
        ///òâåø
        ///òâðåï 
        ///òæøà
        ///òéïâãé
        ///òìéä
        ///òöîåï
        ///òøåâåú
        ///ôãåééí
        ///ôé÷ø
        ///ôåîôãéúà
        ///ôøõ
        ///öàìåï 
        ///öáòåðé
        ///öáø
        ///öéøìñåï
        ///öìó
        ///öéôåøé
        ///÷ãåùéñèøåîä
        ///÷ãù
        ///÷äéìúááì
        ///÷äéìúåéìðä 
        ///÷åîîéåú 
        ///÷å÷ 
        ///÷éùåï
        ///÷øï äéñåã
        ///äøàùåðéí
        ///øáðåúí
        ///øâáéí
        ///øã&quot;÷
        ///øåú 
        ///øæéàì
        ///øçì
        ///øééðñ
        ///øîá&quot;í
        ///øî [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string streetnames {
            get {
                return ResourceManager.GetString("streetnames", resourceCulture);
            }
        }
    }
}
