//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourcesManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אשדוד
        ///באר שבע
        ///אשקלון
        ///רהט
        ///קריית גת
        ///אילת
        ///נתיבות
        ///דימונה
        ///אופקים
        ///שדרות
        ///ערד
        ///קריית מלאכי
        ///ירושלים
        ///בית שמש
        ///ראשון לציון
        ///פתח תקווה
        ///נתניה
        ///רחובות
        ///כפר סבא
        ///לוד
        ///ראש העין
        ///יבנה
        ///אלעד
        ///תל אביב
        ///רמת גן
        ///בת ים
        ///קריית אונו.
        /// </summary>
        internal static string citynames {
            get {
                return ResourceManager.GetString("citynames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_plus {
            get {
                object obj = ResourceManager.GetObject("green_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א
        ///ב
        ///ג
        ///ד
        ///ה
        ///ו
        ///ז
        ///ח
        ///ט
        ///י
        ///כ
        ///ל
        ///מ
        ///נ
        ///ס
        ///ע
        ///פ
        ///צ
        ///ק
        ///ר
        ///ש
        ///ת
        ///ך
        ///ם
        ///ן
        ///ף
        ///ץ.
        /// </summary>
        internal static string hebrewletters {
            get {
                return ResourceManager.GetString("hebrewletters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כהן
        ///לוי
        ///מזרחי
        ///פרץ
        ///ביטון
        ///דהן
        ///אברהם
        ///אגבאריה
        ///פרידמן
        ///מלכה
        ///אזולאי
        ///יוסף
        ///מחאמיד
        ///כץ
        ///ג&apos;בארין
        ///דוד
        ///עמר
        ///חדד
        ///אוחיון
        ///גבאי
        ///ח&apos;טיב
        ///בן דוד
        ///אדרי
        ///קליין
        ///חן
        ///שפירא
        ///זועבי
        ///מחאג&apos;נה
        ///טל
        ///לוין
        ///משה
        ///חזן
        ///אוחנה
        ///סואעד
        ///גולן
        ///סגל
        ///אשכנזי
        ///יצחק
        ///בר
        ///יעקב
        ///מור
        ///שלום
        ///אליהו
        ///דיין
        ///סויסה
        ///לביא
        ///אלבז
        ///שמש
        ///אטיאס
        ///בכר
        ///נחום
        ///שטרן
        ///שרעבי
        ///אלון
        ///רוזנברג
        ///ממן
        ///בן חמו
        ///מימון
        ///שחר
        ///וקנין
        ///ששון
        ///עובדיה
        ///אסולין
        ///שורץ
        ///מאיר
        ///וייס
        ///גרינברג
        ///חסן
        ///אמסלם
        ///גולדשטיין
        ///ברוך
        ///טאהא
        ///מסארוה
        ///עזרא
        ///יפרח
        ///פלדמן
        ///רובין
        ///הראל
        ///סלאמה
        ///סבג [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastnames {
            get {
                return ResourceManager.GetString("lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap missing_profile_photo {
            get {
                object obj = ResourceManager.GetObject("missing-profile-photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אבי
        ///אביאור
        ///אביאל
        ///אביב
        ///אביגדור
        ///אבידור
        ///אבידן
        ///אביה
        ///אביהו
        ///אביחי
        ///אבינועם
        ///אבינר
        ///אביעד
        ///אביר
        ///אבישי
        ///אביתר
        ///אבנר
        ///אברהם
        ///אבשלום
        ///אגם
        ///אדי
        ///אדיר
        ///אדם
        ///אדר
        ///אדריאן
        ///אהוד
        ///אהרון
        ///אודי
        ///אוהד
        ///אוליבר
        ///און
        ///אופיר
        ///אופק
        ///אופרי
        ///אור
        ///אוראל
        ///אורון
        ///אורי
        ///אוריאל
        ///אוריאן
        ///אוריה
        ///אוריין
        ///אורין
        ///אורן
        ///אושיק
        ///אושן
        ///אושר
        ///אושרי
        ///אחיה
        ///אחישי
        ///איב
        ///אידו
        ///אייל
        ///איילון
        ///אילאי
        ///אילון
        ///אילור
        ///אילי
        ///איליי
        ///אילן
        ///אילעאי
        ///אימרי
        ///איציק
        ///איתי
        ///איתיאל
        ///איתם
        ///איתמר
        ///איתן
        ///אלאור
        ///אלאורי
        ///אלדד
        ///אלדר
        ///אלון
        ///אלחי
        ///אלחנן
        ///אלי
        ///אליאב
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort {
            get {
                object obj = ResourceManager.GetObject("sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לכיש
        ///לוחמיהגיטאות
        ///למרחב
        ///מבצעקדש
        ///מגד 
        ///מגידו 
        ///מודיעין
        ///מורן
        ///מוהליבר
        ///מוריה
        ///מסדה
        ///מעייןחרוד
        ///מצדה
        ///מרגנית
        ///מרדכי
        ///נהרדעא
        ///נווה רעים
        ///נורדאו
        ///נורית
        ///נחל בשור
        ///נחל עמוד
        ///נחל קדרון
        ///נחלשורק
        ///נחמיה
        ///נחשון
        ///נטף
        ///ניל&quot;י
        ///נצנה
        ///נעמי
        ///סביון
        ///סולד
        ///נתניהו
        ///סביון
        ///סולד
        ///סוקולוב
        ///סיגלית
        ///סיני
        ///סלע 
        ///סמדר
        ///סנה משה
        ///סנונית
        ///סנש
        ///עבדת
        ///עגור
        ///עגנון 
        ///עזרא
        ///עיןגדי
        ///עליה
        ///עצמון
        ///ערוגות
        ///פדויים
        ///פיקר
        ///פומפדיתא
        ///פרץ
        ///צאלון 
        ///צבעוני
        ///צבר
        ///צירלסון
        ///צלף
        ///ציפורי
        ///קדושיסטרומה
        ///קדש
        ///קהילתבבל
        ///קהילתוילנה 
        ///קוממיות 
        ///קוק 
        ///קישון        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string streetnames {
            get {
                return ResourceManager.GetString("streetnames", resourceCulture);
            }
        }
    }
}
